<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ7rcuoF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ7rcuoF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ7rcuoF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ7rcuoF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ7rcuoF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z7rcuoF',
    'container.build_id' => '4b5db5a5',
    'container.build_time' => 1691048870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ7rcuoF');
